config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'top#index'

  resources :users do
    member do
      get :edit_password 
      patch :update_password
    end
  end
  
  resources :photos, only: [:index, :create, :show, :new]
  resource :follows, only: [:create, :destroy]
  resource :comments, only: [:create]
  resource :favorites, only: [:create, :destroy] 

  resources :notifications, only: [:index]
  resources :guidelines, only: [:index]
  
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#delete'
  
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

end

app/controllers/top_controller.rb
class TopController < ApplicationController

	def index
		if logged_in
			@photos = get_follows_photos
		end
	end
	
	def get_follows_photos
		Photo.where(user_id: get_follows_ids).order(created_at: "DESC")
	end
	
	def get_follows_ids
		Follow.where(user_id: session[:user_id]).pluck(:followed_user_id)
	end

end

app/helpers/top_helper.rb
module TopHelper
end

app/views/top/index.html.erb
<% provide(:title, 'TopPage') %>

<% flash.each do |name, msg| %>
  <div class="alert alert-<%=name%>">
    <%= msg %>
  </div>
<% end %> 

<% if !logged_in %>
  
  <p><%= link_to "Log in with Facebook", user_facebook_omniauth_authorize_path %></p>
  
  <%= form_for(:session, url: login_path) do |f| %>
    <div class="form-group">
      <%= f.label :user_name %>
      <%= f.text_field :user_name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %>
    </div>
    <%= f.submit "Log in", class: "btn btn-primary" %>
  <% end %>
  
  <p>アカウントをお持ちではないですか？ <%= link_to "Sign up", new_user_path %></p>

  <p class="mb-1">※サンプルユーザー</p>
  <p class="mt-1">
    user_name : test1<br>
    password : 111111
  </p>
  
  <p class="mb-1">※サンプルFacebookログインユーザー</p>
  <p class="mt-1">
    email : open_hedibeq_user@tfbnw.net<br>
    password : 104717804552667
  </p>

<% else %>
  
  <% if @photos.length == 0 %>
    <p>フォローユーザーの写真が表示されます。</p>
    <p>気になるユーザーをフォローしてみましょう！</p>
  <% else %>
    <div class="container">
      <% @photos.each do |photo| %>
        <div class="d-flex justify-content-center text-center mb-5">
          <div>
            <p class="mb-1"><%= link_to "#{photo.user.user_name}さん", user_path(id: photo.user_id) %>の写真</p>
            <%= link_to image_tag(photo.content.url), photo_path(id: photo.id) %>
            <%= render 'photos/like', photo: photo %>
            <%= render 'photos/comment', photo: photo%>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
  
<% end %>