config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'top#index'

  resources :users do
    member do
      get :edit_password 
      patch :update_password
    end
  end
  
  resources :photos, only: [:index, :create, :show, :new]
  resource :follows, only: [:create, :destroy]
  resource :comments, only: [:create]
  resource :favorites, only: [:create, :destroy] 

  resources :notifications, only: [:index]
  resources :guidelines, only: [:index]
  
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#delete'
  
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

end

app/models/user.rb
class User < ApplicationRecord
  devise :omniauthable
  
  has_many :photos,  dependent: :destroy
  has_many :follows, class_name: "Follow", foreign_key: "user_id", dependent: :destroy
  has_many :followeds, class_name: "Follow", foreign_key: "followed_user_id", dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :recieve_notification, class_name: "Notification", foreign_key: "reciever_id", dependent: :destroy
  has_many :send_notifification, class_name: "Notification", foreign_key: "sender_id", dependent: :destroy

  validates :name, presence: true
  validates :user_name, presence: true, uniqueness: true
  
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, on: :create
  
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      user.image = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails, 
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end
  
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      log_in(@user)
      flash[:notice] = "Success to LogIn by Facebook"
      redirect_to user_path(@user.id)
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      render template: "users/new"
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, 
    :edit_password, :update_password]

  # GET /users
  # GET /users.json
  def index
    if params[:search]
      if params[:search] == ""
        @search_users = []
      else
        @search_users = User.where('user_name like ?', "%#{params[:search]}%")
      end
    end
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @photos = @user.photos
    @follow_count = @user.follows.size
    @follower_count = @user.followeds.size
    @is_followed_by_current_user = @user.followeds.where(user_id: session[:user_id]).present?
  end

  # GET /users/new
  def new 
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end
  
  def edit_password
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params_create)

    respond_to do |format|
      if @user.save
        log_in(@user)
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params_update)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_password
    if validates_password
      if @user.update(password: params[:user][:new_password]) 
        flash[:notice] = "successs change password"
        redirect_to user_path
      else
        flash[:danger] = "failed to change password by DB error"
        redirect_to edit_password_user_path
      end
    else
      redirect_to edit_password_user_path
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    log_out
    flash[:notice] = "User was successfully destroyed."
    redirect_to root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params_create
      params.require(:user).permit(:name, :user_name, :email, :password, :password_confirmation, :image, :provider, :uid)
    end
    
    def user_params_update
      params.require(:user).permit(:name, :user_name, :web_site, :description, :email, :tel, :sex)
    end
    
    def validates_password 
      if !@user.authenticate(params[:user][:password])
        flash[:danger] = "incorrect password"
        return
      end
      
      if params[:user][:new_password].empty?
        flash[:danger] = "can not blank"
        return
      end
      
      if @user.authenticate(params[:user][:new_password])
        flash[:danger] = "以前のパスワードと同じです。"
        return
      end
      
      if params[:user][:new_password] != params[:user][:new_password_confirmation]
        flash[:danger] = "not match new password"
        return
      end
      
      return true
    end
    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div class="alert alert-danger" id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <% if user.id %>
    <div class="form-group">
      <%= form.label :name %>
      <%= form.text_field :name, id: :user_name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :user_name %>
      <%= form.text_field :user_name, id: :user_user_name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :web_site %>
      <%= form.text_field :web_site, id: :user_web_site, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :description %>
      <%= form.text_field :description, id: :user_description, class: "form-control" %>
    </div>
    <p>非公開情報</p>
    <div class="form-group">
      <%= form.label :email %>
      <%= form.text_field :email, id: :user_email, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :tel %>
      <%= form.text_field :tel, id: :user_tel, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :sex %>
      <%= form.text_field :sex, id: :user_sex, class: "form-control" %>
    </div>
  <% else %>
    <% if user.provider == "facebook" %>
      <div class="form-group">
        <%= form.label :user_name %>
        <%= form.text_field :user_name, id: :user_user_name, class: "form-control" %>
      </div>
      <%= form.hidden_field :name, values: user.name%>
      <%= form.hidden_field :email, values: user.email%>
      <%= form.hidden_field :password, values: user.password%>
      <%= form.hidden_field :image, values: user.image%>
      <%= form.hidden_field :provider, values: user.provider%>
      <%= form.hidden_field :uid, values: user.uid%>
    <% else %>
      <div class="form-group">
        <%= form.label :name %>
        <%= form.text_field :name, id: :user_name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= form.label :user_name %>
        <%= form.text_field :user_name, id: :user_user_name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= form.label "#{:password} (6文字以上)" %>
        <%= form.password_field :password, id: :user_password, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= form.label :password_confirmation %>
        <%= form.password_field :password_confirmation, id: :user_password_confirmation, class: "form-control" %>
      </div>
    <% end %>
  <% end %>
  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/users/_users.html.erb
<% users.each do |user| %>
  <div class="d-flex py-3 my-3 border-top-0 border-right-0 border-left-0 border border-secondary">
    <p><strong>Image:</strong></p>
    <%= image_tag '/default_user_image/default_user_image.png', class: "rounded-circle" %>
    <div class="d-flex my-auto mx-3">
      <%= link_to "#{user.user_name}", user  %>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, 'UserPage') %>

<h1>プロフィール編集ページ</h1>

<%= render 'form', user: @user %>

<% if @user.id %>
  <p>
    <%= link_to 'パスワード変更ページへ', edit_password_user_path %>
  </p>
<% end %>

<%= button_to 'アカウント削除', user_path, method: :delete, class: "btn btn-danger" %>

app/views/users/edit_password.html.erb
<% provide(:title, 'UserPage') %>

<% if flash[:danger] %>
	<div class="alert alert-danger"><%= flash[:danger] %></div>
<% end %>

<%= form_with(model: @user, url: update_password_user_path, local: true) do |f| %>

	<% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<div class="form-group">
		<div class="field">
			<%= f.label :password %>
			<%= f.password_field :password, id: :user_password, class: "form-control" %>
		</div>
	</div>
	
	<div class="form-group">
		<div class="field">
			<%= f.label :new_password %>
			<%= f.password_field :new_password, id: :user_new_password, class: "form-control" %>
		</div>
	</div>
	
	<div class="form-group">
		<div class="field">
			<%= f.label :new_password_confirmation %>
			<%= f.password_field :new_password_confirmation, id: :user_new_password_confirmation, class: "form-control" %>
		</div>
	</div>
	
	
	<div class="action">
		<%= f.submit class: "btn btn-primary" %>
	</div>

<% end %>

app/views/users/index.html.erb
<% provide(:title, 'UsersPage') %>

<p id="notice"><%= notice %></p>

<% if @search_users %>
  <h1 class="text-center">検索結果</h1>
  <% if @search_users.length == 0 %>
    <p class="text-center mb-5">検索結果はありませんでした。</p>
  <% else %>
    <div class="mb-5">
      <%= render 'users', users: @search_users %>
    </div>
  <% end %>
<% end %>

<div class="text-center">
  <h1>All Users</h1>
</div>

<%= render 'users', users: @users %>

app/views/users/new.html.erb
<% provide(:title, 'SignUpPage') %>

<h3>Sign Up</h3>

<%= render partial: 'users/form', locals: { user: @user } %>

<p><%= link_to '利用規約', guidelines_path %></p>

app/views/users/show.html.erb
<% provide(:title, 'UserPage') %>

<%= flash[:danger] %>

<p id="notice"><%= notice %></p>

<div class="profile_top">
  <div class="profile_icon">
    <p><strong>Image:</strong></p>
      <%= image_tag '/default_user_image/default_user_image.png', class: "rounded-circle" %>
  </div>
  <div class="profile_content">
    <p><strong>user_name: </strong><%= @user.user_name %></p>
    <% if is_owner(@user.id) %>
      <p><%= link_to 'プロフィール編集ページ', edit_user_path(@user), class: "btn btn-light" %> </p>
    <% else %>
      <% if @is_followed_by_current_user %>
        <p>フォローしています</p>
        <%= button_to "フォロー解除",
          follows_path({follows: {user_id: current_user, followed_user_id: @user.id}}),
          method: :delete, class: "btn btn-light" %>
      <% else %>
        <%= button_to "フォローする", 
          follows_path({follows: {user_id: current_user, followed_user_id: @user.id}}),
          class: "btn btn-primary" %>
      <% end %>
    <% end %>
  </div>
</div>

<p><strong>Description: </strong><%= @user.description %></p>

<div class="d-flex justify-content-around my-4 border border-secondary border-left-0 border-right-0 ">
  <p><strong>投稿写真数:</strong><%= @photos.size %></p>
  <p><strong>フォロワー:</strong><%= @follower_count %></p>
  <p><strong>フォロー中:</strong><%= @follow_count %></p>
</div>

<%= render 'photos/photos', photos: @photos, remote: true %>

<div id="photo-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>