config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'top#index'

  resources :users do
    member do
      get :edit_password 
      patch :update_password
    end
  end
  
  resources :photos, only: [:index, :create, :show, :new]
  resource :follows, only: [:create, :destroy]
  resource :comments, only: [:create]
  resource :favorites, only: [:create, :destroy] 

  resources :notifications, only: [:index]
  resources :guidelines, only: [:index]
  
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#delete'
  
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :notification, dependent: :destroy
  mount_uploader :content, PhotoUploader
  
  validates :content, presence: true
  validates :user_id, presence: true
  
  def is_favorite_by(favorite_by)
    self.favorites.where(user_id: favorite_by).present?
  end
  
  def get_favorite_count
    self.favorites.count
  end
  
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show]

  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.paginate(page: params[:page], per_page: 12)
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = Photo.new
    @photo.user_id = session[:user_id]
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def photo_params
      params.require(:photo).permit(:content, :user_id)
    end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_comment.html.erb
<%= form_with(model: Comment.new, local:true) do |f| %>
  <%= f.label "Comment" %>
  <%= f.text_field :content %>
  <%= f.hidden_field :user_id, value: current_user%>
  <%= f.hidden_field :photo_id, value: photo.id%>
  <%= f.submit "コメントする" %>
<% end %>

<p>コメント一覧</p>
<% photo.comments.each do |comment| %>
  <p class="my-1"><%= "#{comment.user.user_name}さんのコメント : #{comment.content}"%></p>
<% end %>

app/views/photos/_form.html.erb
<%= form_with(model: photo, local: true) do |form| %>
  <% if photo.errors.any? %>
    <div class="alert alert-danger" id="error_explanation">
      <h2><%= pluralize(photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <div class="field">
      <%= form.label "ファイルをアップロード" %>
      <%= form.file_field :content, value: photo.content, class: "form-control-file" %>
    </div>
  </div>

  <div class="field">
    <%= form.hidden_field :user_id, value: photo.user_id %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/photos/_like.html.erb
<% if photo.is_favorite_by(current_user) %>
  <%= button_to "Like #{photo.get_favorite_count}", favorites_path({favorites: {user_id: current_user, photo_id: photo.id}}),
    method: :delete, class: "btn btn-info my-3" %>
<% else %>
  <%= button_to "Like #{photo.get_favorite_count}", favorites_path({favorites: {user_id: current_user, photo_id: photo.id}}),
    class: "btn btn-outline-info my-3" %>
<% end %>

app/views/photos/_photos.html.erb
<% photos.each_slice(3) do |photo_group| %>
  <div class="photos my-4">
    <% photo_group.each do |photo| %>
      <div class="photo">
        <%= link_to image_tag(photo.content.url), photo_path(id: photo.id), remote: remote %>
      </div>
    <% end %>
    <% if photo_group.count % 3 == 1 %>
      <div class="photo"></div>
      <div class="photo"></div>
    <% elsif photo_group.count % 3 == 2 %>
      <div class="photo"></div>
    <% end %>
  </div>
<% end %>

app/views/photos/_show.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <p id="notice"><%= notice %></p>
    
    <%= flash[:danger] %>
    
    <p><%= image_tag @photo.content.url %></p>
    
    <% if !is_owner(@photo.user_id) %>
      <%= render 'like', photo: @photo %>
    <% end %>
    
    <%= render 'comment', photo: @photo %>
   
  </div>
</div>

app/views/photos/index.html.erb
<% provide(:title, 'PhotosPage') %>

<p id="notice"><%= notice %></p>

<%= will_paginate %>

<%= render 'photos/photos', photos: @photos, remote: false %>

<%= will_paginate %>

app/views/photos/new.html.erb
<% provide(:title, 'PhotoPage') %>

<h1>New Photo</h1>

<%= render 'form', photo: @photo %>

app/views/photos/show.html.erb
<% provide(:title, 'PhotoPage') %>

<p id="notice"><%= notice %></p>

<%= flash[:danger] %>

<p class="mb-1"><%= link_to "#{@photo.user.user_name}さん", user_path(id: @photo.user_id) %>の写真</p>
<p><%= image_tag @photo.content.url %></p>

<% if !is_owner(@photo.user_id) %>
  <%= render 'like', photo: @photo %>
<% end %>

<%= render 'comment', photo: @photo%>

app/views/photos/show.js.erb
$("#photo-modal").html("<%= escape_javascript(render 'show') %>")
$("#photo-modal").modal("show")