config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'top#index'

  resources :users do
    member do
      get :edit_password 
      patch :update_password
    end
  end
  
  resources :photos, only: [:index, :create, :show, :new]
  resource :follows, only: [:create, :destroy]
  resource :comments, only: [:create]
  resource :favorites, only: [:create, :destroy] 

  resources :notifications, only: [:index]
  resources :guidelines, only: [:index]
  
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#delete'
  
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstaClone : <%= yield(:title) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="wrapper">
      <header>
        <div class="navbar navbar-light navbar-expand-md bg-light d-flex justify-content-between">
          <div>
            <%= link_to 'Instagram', root_path %>
          </div>
          
          <% if logged_in %>
            <div>
              <%= form_with(url: users_path, local: true, method: :get) do |f| %>
                <div class="form-group my-auto">
                  <%= f.search_field :search, id: :search, placeholder: "ユーザー検索", class: "form-control form-control-sm" %>
                </div>
              <% end %>
            </div>
            
            <div>
              <button class="navbar-toggler" data-toggle="collapse" data-target="#menu">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div id="menu" class="collapse navbar-collapse">
                <ui class="navbar-nav">
                  <li><%= link_to 'MyPage', user_path(id: current_user), class: "nav_item mx-1" %></li>
                  <li>
                    <% if has_notification %>
                      <%= link_to '通知', notifications_path, class: "nav_item mx-1 fa fa-circle" %>
                    <% else %>
                      <%= link_to '通知', notifications_path, class: "nav_item mx-1" %>
                    <% end %>
                  </li>
                  <li><%= link_to 'User一覧', users_path, class: "nav_item mx-1" %></li>
                  <li><%= link_to '写真一覧', photos_path, class: "nav_item mx-1" %></li>
                  <li><%= link_to 'LogOut', logout_path, class: "nav_item mx-1" %></li>
                </ui>
              </div>
            </div>
          <% end %>
        </div>
      </header>
      <main>
        <div class="container">
          <%= yield %>
        </div>
      </main>
      <% if logged_in %>
        <footer class="bg-light pt-2">
          <%= link_to '写真投稿', new_photo_path, class: "btn btn-primary" %>
        </footer>
      <% end %>
    </div>
  </body>
  
</html>